# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: python:3.5.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          # - apt-get install mercurial
          - pip install -r requirements.txt
          - pip install -r requirements.test.txt
          - pyinstaller -D -F -n df-translate -w "df-translate.pyw"
          - ls build
